import 'package:flutter/material.dart%20';

import 'global_booking.dart';

const kSalonName = '';
const kLogoAdress = '';
const kAdress = '';
const kAbout = '';
const ktimeopen = '';
const kContactNumber = '';

//Andriod/App/Buildgra.. application Id
//Get Church infrommation
//Use the Church table
//
// Future<Map<String, dynamic>> getChurch(ChurchName) async {
//   final data = await supabase.from('Church').select(ChurchName).single();
//   return data;
// }
//
const Map<String, Map<String, dynamic>> projects = {
  'Project': {
    'ChurchName': 'Heaven on Earth \nHair and Beauty Salon',

    'LogoAddress': 'lib/images/logoh.png',

    'Address':
        '1st Floor, 3rd Rock Entrance,\nSmith Street, 494, Durban Central, Durban, 4000',

    'Read': 'Beauty,cosmetic & personal care.',
    'Gps Lat': '-29.860499',
    'Gps Long': '31.016267',
    'About': '',
    'TimeOpen': 'Monday to Sunday ( 07:00 - 19:00 )',
    'ContactNumber': '+27 60 452 0742 & \n+27 73 959 6368',
    'Color': Color(0xFFF99604),
    'URL': 'https://bmzconrnjgpbiapvqcfh.supabase.co',
    'API': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImljaG52dW1mem9iaWdza3lyb2VqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTUzNjUyMDYsImV4cCI6MjAzMDk0MTIwNn0.UgA32sjsuwQav3QHB7q7fhcCTzQZ8qcihD9NLIvQpsI',
    'ProjectId': '663e70370012ecbb3ba5',
    'Bucket': 'HeavenEarth',
  },
};
//
// const Map<String, Map<String, dynamic>> extra = {
//   'Project': {
//     'SalonName': 'Quinten’s hair salon',
//     'LogoAddress': 'lib/images/logoqq.png',
//     'Address': '513 Smith Street',
//     'Read': 'Beauty,cosmetic & personal care.',
//     'Gps Lat': '-29.86109279114517',
//     'Gps Long': '31.014298324827156',
//     'About': '',
//     'TimeOpen': '',
//     'ContactNumber': '078 704 3073',
//     'Color': Colors.pinkAccent,
//     'URL': 'https://wztukpqyhpgokqgaaomr.supabase.co',
//     'API':
//         'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6dHVrcHF5aHBnb2txZ2Fhb21yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTQ0Mjg5MTYsImV4cCI6MjAzMDAwNDkxNn0.ReiVjU9GhG9XUKMMw51eR8Va1bEK5autgES919wFHfs',
//     'ProjectId': '66301d86002ed7cdf75b',
//     'Bucket': 'quitensLady',
//   },
//
//   'Beauty By Thule': {
//     'SalonName': 'Beauty By Thule',
//     'LogoAddress': 'lib/images/logo.jpeg',
//     'Address': '535 Anton Lembede Street, Smith Street',
//     'Read': 'Beauty,cosmetic & personal care.',
//     'Gps Lat': '-29.86109279114517',
//     'Gps Long': '31.014298324827156',
//     'About': '',
//     'TimeOpen': '',
//     'ContactNumber': '078 704 3073',
//     'Color': Colors.pinkAccent,
//     'URL': 'https://subejxnzdnqyovwhinle.supabase.co',
//     'API':
//         'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1YmVqeG56ZG5xeW92d2hpbmxlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDg1NDI5NTMsImV4cCI6MjAyNDExODk1M30.hDMsQXcPhdq-ZE126aPOYMIZVmnU6xOQjeLwxOijHrs',
//     'Times': [
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//     ]
//   },
//
//   'Quinten’s hair salon': {
//     'SalonName': 'Quinten’s hair salon',
//     'LogoAddress': 'lib/images/logoqq.png',
//     'Address': '513 Smith Street',
//     'Read': 'Beauty,cosmetic & personal care.',
//     'Gps Lat': '-29.8608669818928',
//     'Gps Long': '31.015210582498774',
//     'About': '',
//     'TimeOpen': '08:00 to 7:00pm',
//     'ContactNumber': '0815679094',
//     'Color': Colors.pinkAccent,
//     'URL': 'https://xxjgdxjarfgmzywkzwsn.supabase.co',
//     'API':
//         'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4amdkeGphcmZnbXp5d2t6d3NuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTQyMTYxNTQsImV4cCI6MjAyOTc5MjE1NH0.A80flYOObXRnQa9rb7yB4jDlDOT2MFFc0De0O4SzDnE',
//     'ProjectId': '662cf6ea00088572ee35',
//     'Bucket': 'quitensLady',
//     'Times': [
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//     ]
//   },
//
//   // 'projects['Project']?['Bucket']'
//   'Quinten’s hair salon...': {
//     'SalonName': 'Quinten’s hair salon',
//     'LogoAddress': 'lib/images/logoqq.png',
//     'Address': '567 matham Gandhi road',
//     'Read': 'Beauty,cosmetic & personal care.',
//     'Gps Lat': '-29.857061769665464',
//     'Gps Long': '31.03620450970444',
//     'About': '',
//     'TimeOpen': '08:30 to 8:00pm',
//     'ContactNumber': '0765430947',
//     'Color': Colors.pinkAccent,
//     'URL': 'https://xxjgdxjarfgmzywkzwsn.supabase.co',
//     'API':
//         'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4amdkeGphcmZnbXp5d2t6d3NuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTQyMTYxNTQsImV4cCI6MjAyOTc5MjE1NH0.A80flYOObXRnQa9rb7yB4jDlDOT2MFFc0De0O4SzDnE',
//     'ProjectId': '662cf6ea00088572ee35',
//     'Bucket': 'quitensMino',
//     'Times': [
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//       'Morning',
//       'Afternoon',
//     ]
//   },
//
//   'Salon2 ': {
//     'kSalonName': '',
//     'LogoAdress': '',
//     'Adress': '',
//     'About': '',
//     'TimeOpen': '',
//     'ContactNumber': '',
//   },
//
//   'Salon3 ': {
//     'kSalonName': '',
//     'LogoAdress': '',
//     'Adress': '',
//     'About': '',
//     'TimeOpen': '',
//     'ContactNumber': '',
//   }
// };
