// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDci6p5WnellIgN0DI9JgI07rHQPgguaCY',
    appId: '1:275828296017:web:67266803013609e40f6b70',
    messagingSenderId: '275828296017',
    projectId: 'salon-app-84e5c',
    authDomain: 'salon-app-84e5c.firebaseapp.com',
    storageBucket: 'salon-app-84e5c.appspot.com',
    measurementId: 'G-ZFP2C8CBD3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI-fo4u6KddF4i2frGxBiMGxRgPJqWLww',
    appId: '1:275828296017:android:12dc5d5deb64a3330f6b70',
    messagingSenderId: '275828296017',
    projectId: 'salon-app-84e5c',
    storageBucket: 'salon-app-84e5c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJlLBOqgwme4S3MoxJLDLz_Ie8pxnE5OU',
    appId: '1:275828296017:ios:af13d1552d90916b0f6b70',
    messagingSenderId: '275828296017',
    projectId: 'salon-app-84e5c',
    storageBucket: 'salon-app-84e5c.appspot.com',
    iosBundleId: 'com.example.master',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJlLBOqgwme4S3MoxJLDLz_Ie8pxnE5OU',
    appId: '1:275828296017:ios:8482b3b6bdeb18160f6b70',
    messagingSenderId: '275828296017',
    projectId: 'salon-app-84e5c',
    storageBucket: 'salon-app-84e5c.appspot.com',
    iosBundleId: 'com.example.master.RunnerTests',
  );
}
