// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8AHJjI_KDjtCXlpMv2917Jcrk_Cz8Ev8',
    appId: '1:301652956348:android:3b52c27f0c4880c83e6cb9',
    messagingSenderId: '301652956348',
    projectId: 'churchconnect-8157d',
    storageBucket: 'churchconnect-8157d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt-U7GH5mntxgs38NRbYzqLIXmPSAv9Jo',
    appId: '1:301652956348:ios:382e3dcd79a110d03e6cb9',
    messagingSenderId: '301652956348',
    projectId: 'churchconnect-8157d',
    storageBucket: 'churchconnect-8157d.firebasestorage.app',
    iosBundleId: 'com.example.master',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt-U7GH5mntxgs38NRbYzqLIXmPSAv9Jo',
    appId: '1:301652956348:ios:382e3dcd79a110d03e6cb9',
    messagingSenderId: '301652956348',
    projectId: 'churchconnect-8157d',
    storageBucket: 'churchconnect-8157d.firebasestorage.app',
    iosBundleId: 'com.example.master',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC68W0ODoBk8taha9W08fVZcRbHUEbYUm0',
    appId: '1:301652956348:web:d24f2d1628bec27d3e6cb9',
    messagingSenderId: '301652956348',
    projectId: 'churchconnect-8157d',
    authDomain: 'churchconnect-8157d.firebaseapp.com',
    storageBucket: 'churchconnect-8157d.firebasestorage.app',
    measurementId: 'G-15GD1R73H9',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC68W0ODoBk8taha9W08fVZcRbHUEbYUm0',
    appId: '1:301652956348:web:5773e288b7f491633e6cb9',
    messagingSenderId: '301652956348',
    projectId: 'churchconnect-8157d',
    authDomain: 'churchconnect-8157d.firebaseapp.com',
    storageBucket: 'churchconnect-8157d.firebasestorage.app',
    measurementId: 'G-6BBJLB1FXN',
  );

}